services:

  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vidx:${VIDX_VERSION:-latest}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      VIDX_HOST: 0.0.0.0
      VIDX_DB_HOST: vidx-db
      VIDX_DB_PORT: 27017
      VIDX_DB_USER: vidx
      VIDX_DB_PASS: vidx
      VIDX_DB_BASE: admin
      RABBITMQ_HOST: vidx-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: vidx
      RABBITMQ_PASS: vidx
      RABBITMQ_BASE: /

  db:
    image: mongo:7.0
    hostname: vidx-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "vidx"
      MONGO_INITDB_ROOT_PASSWORD: "vidx"
    command: "mongod"
    volumes:
      - db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 40
  rabbitmq:
    image: rabbitmq:3-management
    hostname: vidx-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: vidx
      RABBITMQ_DEFAULT_PASS: vidx
    volumes:
      - config-rabbitmq:/var/lib/rabbitmq
      - db-rabbitmq:/data

  celery:
    <<: *main_app # inherit all the settings from the main app
    command: poetry run start-celery
    depends_on:
      - api
      - rabbitmq

volumes:
  db-data:
  db-rabbitmq:
  config-rabbitmq:
