services:

  redis:
    image: bitnami/redis:6.2.5
    hostname: "vidx-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

volumes:
  vidx-db-data:
    name: vidx-db-data
